path_source: "/Volumes/Work/"
path_dest: "gregory@lab.easyflirt.com:/data/users/gregory/"
rsync: "/usr/local/bin/rsync"
rsync_opts: "-rlptz --delete"
excludes:
  - '\..+?/'
  - '/Storage/'
rsync_excludes: 
  - "/.Spotlight-V100/"
  - "/.Trashes/"
  - "/.fseventsd/"
  - "/Storage/"
